### ISSUE TITLE
ParaelTest启动2000线程部分线程会NullPointerException

### ISSUE THREAD

**Issue by shuangyueliao** [PaulWang92115/RPC#1]
运行rpc-consumer模块中的App.java一切正常，但运行ParaeTest.java去启动2000线程，无OOM但偶尔部分线程会NullPointerException
```
{com.paul.framework.URL@8631cefd=[[id: 0x72f82456, L:/192.168.99.1:8671 - R:/192.168.99.1:3230], [id: 0x74c44fab, L:/192.168.99.1:8692 - R:/192.168.99.1:3230]]}
{com.paul.framework.URL@8631cefd=[[id: 0x8bfc4c4f, L:/192.168.99.1:8608 - R:/192.168.99.1:3230], [id: 0xff8bb96e, L:/192.168.99.1:8629 - R:/192.168.99.1:3230], [id: 0x7cbe28f8, L:/192.168.99.1:8650 - R:/192.168.99.1:3230], [id: 0x72f82456, L:/192.168.99.1:8671 - R:/192.168.99.1:3230], [id: 0x74c44fab, L:/192.168.99.1:8692 - R:/192.168.99.1:3230]]}
{com.paul.framework.URL@8631cefd=[]}
{com.paul.framework.URL@8631cefd=[]}
{com.paul.framework.URL@8631cefd=[]}
{com.paul.framework.URL@8631cefd=[]}
{com.paul.framework.URL@8631cefd=[]}
{com.paul.framework.URL@8631cefd=[[id: 0x72f82456, L:/192.168.99.1:8671 - R:/192.168.99.1:3230], [id: 0x74c44fab, L:/192.168.99.1:8692 - R:/192.168.99.1:3230]]}
{com.paul.framework.URL@8631cefd=[]}
release:be8dcd1e
result is:3934
release:be8dcd1e
result is:3932
Exception in thread "Thread-163" java.lang.NullPointerException
	at com.sun.proxy.$Proxy6.cal(Unknown Source)
	at com.paul.service.CalcParallelRequestThread.run(CalcParallelRequestThread.java:34)
	at java.lang.Thread.run(Thread.java:748)
release:7cbe28f8
Exception in thread "Thread-190" java.lang.NullPointerException
release:bceaf4d0
	at com.sun.proxy.$Proxy6.cal(Unknown Source)
	at com.paul.service.CalcParallelRequestThread.run(CalcParallelRequestThread.java:34)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-160" java.lang.NullPointerException
```

出错的地方就在ParaeTest.java的第34行左右的代码
`int result = helloService.cal(taskNumber,taskNumber);`
rpc并发调用有bug，求解惑，谢谢

**Comment by shuangyueliao** [comment]
> 运行rpc-consumer模块中的App.java一切正常，但运行ParaeTest.java去启动2000线程，无OOM但偶尔部分线程会NullPointerException
> 
> ```
> {com.paul.framework.URL@8631cefd=[[id: 0x72f82456, L:/192.168.99.1:8671 - R:/192.168.99.1:3230], [id: 0x74c44fab, L:/192.168.99.1:8692 - R:/192.168.99.1:3230]]}
> {com.paul.framework.URL@8631cefd=[[id: 0x8bfc4c4f, L:/192.168.99.1:8608 - R:/192.168.99.1:3230], [id: 0xff8bb96e, L:/192.168.99.1:8629 - R:/192.168.99.1:3230], [id: 0x7cbe28f8, L:/192.168.99.1:8650 - R:/192.168.99.1:3230], [id: 0x72f82456, L:/192.168.99.1:8671 - R:/192.168.99.1:3230], [id: 0x74c44fab, L:/192.168.99.1:8692 - R:/192.168.99.1:3230]]}
> {com.paul.framework.URL@8631cefd=[]}
> {com.paul.framework.URL@8631cefd=[]}
> {com.paul.framework.URL@8631cefd=[]}
> {com.paul.framework.URL@8631cefd=[]}
> {com.paul.framework.URL@8631cefd=[]}
> {com.paul.framework.URL@8631cefd=[[id: 0x72f82456, L:/192.168.99.1:8671 - R:/192.168.99.1:3230], [id: 0x74c44fab, L:/192.168.99.1:8692 - R:/192.168.99.1:3230]]}
> {com.paul.framework.URL@8631cefd=[]}
> release:be8dcd1e
> result is:3934
> release:be8dcd1e
> result is:3932
> Exception in thread "Thread-163" java.lang.NullPointerException
> 	at com.sun.proxy.$Proxy6.cal(Unknown Source)
> 	at com.paul.service.CalcParallelRequestThread.run(CalcParallelRequestThread.java:34)
> 	at java.lang.Thread.run(Thread.java:748)
> release:7cbe28f8
> Exception in thread "Thread-190" java.lang.NullPointerException
> release:bceaf4d0
> 	at com.sun.proxy.$Proxy6.cal(Unknown Source)
> 	at com.paul.service.CalcParallelRequestThread.run(CalcParallelRequestThread.java:34)
> 	at java.lang.Thread.run(Thread.java:748)
> Exception in thread "Thread-160" java.lang.NullPointerException
> ```
> 
> 出错的地方就在ParaeTest.java的第34行左右的代码
> `int result = helloService.cal(taskNumber,taskNumber);`
> rpc并发调用有bug，求解惑，谢谢

因为超时返回的结果是null，而CalcParallelRequestThread的35行，helloService.cal方法返回是int，当返回null时，无法将null转成int，就产生NullPointerException，应该在MessageCallBack.java中的start方法中添加超时的时候抛出一个超时的自定义异常，否则就只会抛出NullPointerException，不利于问题的排查
